import {
  faBook, faStar, faHeart, faFlag, faTag, faFolder, faFolderOpen,
  faHome, faUser, faCog, faBell, faCalendar, faClock, faCamera,
  faImage, faFile, faFileLines, faFilePdf, faDownload, faUpload,
  faTrash, faPencil, faPlus, faMinus, faSearch, faFilter,
  faGlobe, faMap, faLocationDot, faPhone, faEnvelope, faLink,
  faLock, faKey, faShield, faBolt, faFire, faLightbulb,
  faChartBar, faChartPie, faChartLine, faList, faListUl, faListOl,
  faCheck, faCheckCircle, faCircle, faSquare, faXmark,
  faArrowRight, faArrowLeft, faChevronRight, faChevronLeft,
  faChevronUp, faChevronDown, faExpand, faCompress, faPlay,
  faPause, faStop, faMusic, faHeadphones, faVideo, faTv,
  faBookmark, faClipboard, faPaperclip, faPrint, faShare,
  faWifi, faBatteryFull, faSignal, faSun, faMoon, faCloud,
  faDroplet, faSnowflake, faLeaf, faSeedling, faTree,
  faBuilding, faStore, faHospital, faSchool, faGift,
  faCakeCandles, faCoffee, faMugHot, faUtensils, faCar,
  faBicycle, faPlane, faShip, faTrain, faBus,
  faDog, faCat, faPaw, faRocket, faGem, faTrophy,
  faMedal, faCrown, faGraduationCap, faPaintBrush,
  faPalette, faWandMagicSparkles, faCode, faDatabase,
  faServer, faKeyboard, faDisplay, faLaptop,
} from '@fortawesome/free-solid-svg-icons'

const ICON_MAP: Record<string, any> = {
  book: faBook, star: faStar, heart: faHeart, flag: faFlag, tag: faTag,
  folder: faFolder, 'folder-open': faFolderOpen,
  home: faHome, user: faUser, cog: faCog, bell: faBell,
  calendar: faCalendar, clock: faClock, camera: faCamera,
  image: faImage, file: faFile, 'file-lines': faFileLines, 'file-pdf': faFilePdf,
  download: faDownload, upload: faUpload, trash: faTrash, pencil: faPencil,
  plus: faPlus, minus: faMinus, search: faSearch, filter: faFilter,
  globe: faGlobe, map: faMap, pin: faLocationDot, phone: faPhone,
  envelope: faEnvelope, link: faLink, lock: faLock, key: faKey,
  shield: faShield, bolt: faBolt, fire: faFire, lightbulb: faLightbulb,
  'chart-bar': faChartBar, 'chart-pie': faChartPie, 'chart-line': faChartLine, 'graph-up': faChartLine,
  list: faList, 'list-ul': faListUl, 'list-ol': faListOl,
  check: faCheck, 'check-circle': faCheckCircle, circle: faCircle,
  square: faSquare, xmark: faXmark,
  'arrow-right': faArrowRight, 'arrow-left': faArrowLeft,
  'chevron-right': faChevronRight, 'chevron-left': faChevronLeft,
  'chevron-up': faChevronUp, 'chevron-down': faChevronDown,
  expand: faExpand, compress: faCompress, play: faPlay,
  pause: faPause, stop: faStop, music: faMusic, headphones: faHeadphones,
  video: faVideo, tv: faTv,
  bookmark: faBookmark, clipboard: faClipboard, paperclip: faPaperclip,
  print: faPrint, share: faShare,
  wifi: faWifi, 'battery-full': faBatteryFull, signal: faSignal,
  sun: faSun, moon: faMoon, cloud: faCloud,
  droplet: faDroplet, snowflake: faSnowflake, leaf: faLeaf,
  seedling: faSeedling, tree: faTree,
  building: faBuilding, store: faStore, hospital: faHospital,
  school: faSchool, gift: faGift, 'cake-candles': faCakeCandles,
  coffee: faCoffee, mug: faMugHot, utensils: faUtensils,
  car: faCar, bicycle: faBicycle, plane: faPlane, ship: faShip,
  train: faTrain, bus: faBus,
  dog: faDog, cat: faCat, paw: faPaw, rocket: faRocket,
  gem: faGem, trophy: faTrophy, medal: faMedal, crown: faCrown,
  'graduation-cap': faGraduationCap, 'paint-brush': faPaintBrush,
  palette: faPalette, 'wand-magic-sparkles': faWandMagicSparkles,
  code: faCode, database: faDatabase, server: faServer,
  keyboard: faKeyboard, display: faDisplay, laptop: faLaptop,
}

export const ICON_NAMES = Object.keys(ICON_MAP)

export function iconLookup(name: string): any {
  return ICON_MAP[name] || faFile
}
